import { animeInfoOptions, IanimeInfo } from "../types";

export default class animeInfo implements IanimeInfo {
    private _name: string;
    private _alias: string[];
    private _id: number;
    private _options: animeInfoOptions;

    constructor(name: string, alias: string[], id: number, options: animeInfoOptions = {}) {
        this._name = name;
        this._alias = alias;
        this._id = id;
        this._options = options;
    };

    get name() {
        return this._name;
    };
    get alias() {
        return this._alias;
    };
    get id() {
        return this._id;
    };
    get options() {
        return this._options;
    };

    get thumbnailCharId() {
        return this.options.charid;
    };
};

export const anime: animeInfo[] = [
    new animeInfo("One Piece", ["OP"], 0),
    new animeInfo("Demon Slayer", ["Kimetsu no Yaiba", "DS", "KnY"], 1),
    new animeInfo("Gotoubun no Hanayome", ["5-toubun no Hanayome", "The Quintessential Quintuplets", "Quintessential Quintuplets", "QQ"], 2),
    new animeInfo("Gosick", [], 3),
    new animeInfo("Horimiya", [], 4),
    new animeInfo("Grimgar: Ashes and Illusions", ["Hai to Gensou no Grimgar", "Grimgar Ashes and Illusions", "Grimgar"], 5),
    new animeInfo("Rec", [], 6),
    new animeInfo("Dororo", [], 7),
    new animeInfo("Katanagatari", [], 8),
    new animeInfo("Fumetsu no Anata e", ["To Your Eternity"], 9),
    new animeInfo("Sword Art Online", ["SAO", "Alicization", "Ordinal Scale", "War of Underworld", "Gun Gale Online"], 10),
    new animeInfo("Your Lie in April", ["Shigatsu wa Kimi no Uso", "YLiA"], 11),
    new animeInfo("Asobi Asobase", [], 12),
    new animeInfo("Eden of The East", ["Higashi no Eden", "HnE", "EotE"], 13),
    new animeInfo("Angel Beats!", ["Angel Beats"], 14),
    new animeInfo("Psycho Pass", ["Psycho-Pass"], 15),
    new animeInfo("Vivy: Fluorite Eye's Song", ["Vivy -Fluorite Eye's Song-", "Vivy"], 16),
    new animeInfo("That Time I Got Reincarnated as a Slime", ["Tensei shitara Slime Datta Ken", "Slime", "Tensura"], 17),
    new animeInfo("Attack on Titan", ["Shingeki no Kyojin", "AoT"], 18),
    new animeInfo("Kuroko no Basket", ['Kuroko no Basuke', 'The Basketball Which Kuroko Plays', "Kuroko's Basketball", 'KuroBas', 'KnB', 'Kurokos Basketball', 'Kuroko'], 19),
    new animeInfo("Tonikaku Kawaii", ["Tonikawa"], 20),
    new animeInfo("Remake our Life!", ["Bokutachi no Remake", "Remake our Life"], 21),
    new animeInfo("Dantalian no Shoka", ["The Mystic Archives of Dantalian"], 22),
    new animeInfo("Your Name", ["Kimi no Na wa"], 23),
    new animeInfo("Happy Sugar Life", ['White Sugar Garden, Black Salt Cage', 'HSL'], 24),
    new animeInfo("Rent-a-Girlfriend", ["Kanojo, Okarishimasu", "Kanojo Okarishimasu", "Rent a Girlfriend", "Kanokari"], 25),
    new animeInfo("Fate Series", ["Fate", "Fate/stay night", "Fate stay night", "Fate/Zero", "Fate Zero", "Fate/Apocrypha", "Fate Apocrypha", "Fate/Kaleid", "Fate Kaleid", "Fate Kaleid Liner Prisma Illya", "Fate/Prototype", "Fate/Grand Order", "Fate Grand Order", "F/", "FGO"], 26),
    new animeInfo("Mushoku Tensei", ["Mushoku Tensei: Isekai Ittara Honki Dasu", "Mushoku Tensei: Jobless Reincarnation"], 27),
    new animeInfo("Haikyuu!!", ["Haikyuu", "Haikyu"], 28),
    new animeInfo("Yamada-kun to 7-nin no Majo", ["Yamada-kun", "Yamada kun", "Yamada-kun and the Seven Witches"], 29),
    new animeInfo("Genshin Impact", ["Genshin", "GI"], 30),
    new animeInfo("No Game No Life", ["NGNL", "No Game, No Life"], 31),
    new animeInfo("Tales of Zestiria the X", ["Tales of Zestiria", "Tales of Zestiria the Cross", "ToZ"], 32),
    new animeInfo("Kono Subarashii Sekai ni Shukufuku wo!", ["God's Blessings on this Wonderful World", "KonoSuba", "KS"], 33),
    new animeInfo("Prison School", ["Kangoku Gakuen"], 34),
    new animeInfo("Golden Boy", [], 35),
    new animeInfo("Ijiranaide, Nagatoro-san", ["Nagatoro", "Don't Toy with Me, Miss Nagatoro", "Please don't bully me, Nagatoro", "Ijiranaide Nagatoro-san"], 36),
    new animeInfo("I sold my life for ten thousand yen per year", ["I sold my life", "Three Days of Happiness", "Mikkakan no Koufuku", "Jumyou wo Kaitotte Moratta. Ichinen ni Tsuki, Ichimanen de."], 37),
    new animeInfo("Vinland Saga", ["Vinland", "VS"], 38),
    new animeInfo("Darling in the FranXX", ["DarliFra", "DitF"], 39),
    new animeInfo("Bunny Girl Senpai", ["Bunny Girl", "Rascal Does Not Dream of Bunny Girl Senpai", "Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai"], 40),
    new animeInfo("Magi", ["Magi: The Labyrinth of Magic", "Magi: The Kingdom of Magic"], 41),
    new animeInfo("Jujutsu Kaisen", ["JJK", "Sorcery Fight"], 42),
    new animeInfo("Uramichi Oniisan", ["Life Lessons with Uramichi-Oniisan"], 43),
    new animeInfo("Grand Blue", ["Grand Blue Dreaming"], 44),
    new animeInfo("Death Note", ["DN"], 45),
    new animeInfo("Link Click", ["Shiguang Dailiren", "Shi Guang Dai Li Ren", "LC"], 46),
    new animeInfo("Odd Taxi", ["ODDTAXI"], 47),
    new animeInfo("Maquia", ["SayoAsa", "Sayonara no Asa ni Yakusoku no Hana wo Kazarou", "Maquia: When the Promised Flower Blooms"], 48),
    new animeInfo("Hotarubi no Mori e", ["HnMe", "The Light of a Firefly Forest", "Into the Forest of Fireflies"], 49),
    new animeInfo("Shelter", [], 50),
    new animeInfo("Hige wo Soru", ["HigeHiro", "Hige wo Soru. Soshite Joshikousei wo Hirou.", "I Shaved and Took in a High School Runaway"], 51),
    new animeInfo("Kill la Kill", ["KLK"], 52),
    new animeInfo("Evangelion", ["Eva", "Neon Genesis Evangelion", "Shinseiki Evangelion"], 53),
    new animeInfo("Noragami", ["Noragami Aragoto"], 54),
    new animeInfo("Mieruko-chan", ["Mieruko", "Mieruko chan"], 55),
    new animeInfo("Takt op. Destiny", ["Takt Op", "Takt Op Destiny", "Takt Op.Destiny"], 56),
    new animeInfo("A Whisker Away", ["Nakitai Watashi wa Neko wo Kaburu"], 57),
    new animeInfo("Cheat Slayer", ["Isekai Tenseisha Koroshi"], 58),
    new animeInfo("Wolf Children", ["Ookami Kodomo no Ame to Yuki"], 59),
    new animeInfo("Danna ga Nani wo Itteiru ka Wakaranai Ken", ["Danna ga Nani", "I Can't Understand What My Husband Is Saying"], 60),
    new animeInfo("Shinchou Yuusha", ["Cautious Hero", "Tueee", "Kono Yuusha ga Ore Tueee Kuse ni Shinchou Sugiru"], 61),
    new animeInfo("I want to eat your pancreas", ["Kimi no Suizou wo Tabetai", "Pancreas"], 62),
    new animeInfo("Grave of the Fireflies", ["Hotaru no Haka"], 63),
    new animeInfo("Redo of Healer", ["Healer", "KJnY", "Kaifuku Jutsushi no Yarinaoshi"], 64),
    new animeInfo("Kaguya-sama: Love is War", ["Kaguya-sama", "Kaguya sama", "Kaguya", "Kaguya-sama wa Kokurasetai"], 65),
    new animeInfo("Trapped in a Dating Sim", ["MobuSeka", "Otome Game Sekai wa Mob ni Kibishii Sekai desu", "The World of Otome Games is Tough for Mobs"], 66),
    new animeInfo("Overlord", [], 67),
    new animeInfo("Wonder Egg Priority", ["WEP", "Wonder Egg"], 68),
    new animeInfo("Heike Monogatari", ["Heike"], 69),
    new animeInfo("Death Parade", [], 70),
    new animeInfo("Guilty Crown", ["GC"], 71),
    new animeInfo("A Silent Voice", ["Koe no Katachi", "The Shape of Voice", "ASV"], 72),
    new animeInfo("High School DxD", ["DxD", "Highschool DxD", "HSDxD"], 73),
    new animeInfo("Code Geass", ["CG", "Code Geass: Hangyaku no Lelouch"], 74),
    new animeInfo("Tate no Yuusha no Nariagari", ["The Rising of the Shield Hero", "Tate no Yuusha", "Shield Hero"], 75),
    new animeInfo("Spirited Away", ["Sen to Chihiro no Kamikakushi", "Sen to Chihiro"], 76),
    new animeInfo("Tenki no Ko", ["TnK", "Weathering With You"], 77),
    new animeInfo("Ookami-san Series", ["Ookami-san to Shichinin no Nakama-tachi", "Okami-San and Her Seven Companions", "Ookami-san"], 78),
    new animeInfo("Toradora!", ["Toradora", "Tiger X Dragon"], 79),
    new animeInfo("Kamisama ga Uso wo Tsuku.", ["Kamisama ga Uso wo Tsuku", "The Gods Lie.", "The Gods Lie"], 80),
    new animeInfo("Tsukihime", ["Shingetsutan Tsukihime", "Lunar Legend Tsukihime", "Lunar Legend Moon Princess", "Moon Princess"], 81),
    new animeInfo("Yahari Ore no Seishun Love Comedy wa Machigatteiru.", ["Yahari Ore no Seishun Love Comedy wa Machigatteiru", "My Teen Romantic Comedy SNAFU", "SNAFU", "My youth romantic comedy is wrong as I expected", "Oregairu"], 82),
    new animeInfo("Somali to Mori no Kamisama", ["SFS", "SMK", "Somali and the Forest Spirit"], 83),
    new animeInfo("Akame ga Kill!", ["Akame ga Kill", "AgK", "Akame", "Akame ga Kiru!", "Akame ga Kiru"], 84),
    new animeInfo("Senran Kagura", ["SK", "Senran"], 85),
    new animeInfo("Harukana Receive", [], 86),
    new animeInfo("Baby Steps", [], 87),
    new animeInfo("Isekai Cheat Magician", ["ICM"], 88),
    new animeInfo("Youjo Senki", ["The Saga of Tanya the Evil", "Saga of Tanya the Evil", "Tanya the Evil"], 89),
    new animeInfo("Summer Ghost", [], 90),
    new animeInfo("World Trigger", ["WT"], 91),
    new animeInfo("Zankyou no Terror", ["Terror in Resonance"], 92),
    new animeInfo("Keijo!!!!!!!!", ["Keijo", "Hip Whip Girl"], 93),
    new animeInfo("Yuri!!! on Ice", ["Yuri on Ice", "Yuri", "YoI"], 94),
    new animeInfo("Kenja no Mago", ["Wise Man's Grandchild", "KnM"], 95),
    new animeInfo("Big Order", ["BO"], 96),
    new animeInfo("BOFURI: I Don't Want to Get Hurt, so I'll Max Out My Defense.", ["Bofuri", "Itai no wa Iya nano de Bougyoryoku ni Kyokufuri Shitai to Omoimasu", "I Hate Being in Pain", "so I Think I'll Make a Full Defense Build", "Itai no wa Iya Nanode"], 97),
    new animeInfo("Shinmai Maou no Testament", ["The Testament of Sister New Devil", "SMnT", "Testament", "Testament of Sister", "Testament of Sister New Devil"], 98),
    new animeInfo("Solo Leveling", ["I Alone Level Up", "I Level Up Alone", "Only I Level Up", "SL"], 99),
    new animeInfo("Kakegurui", ["Gambling School", "Kakegurui: Compulsive Gambler"], 100),
    new animeInfo("UnOrdinary", ["UO", "UnO"], 101),
    new animeInfo("Yowamushi Pedal", ["YowaPeda", "YP"], 102),
    new animeInfo("Fire Emblem", ["FE", "FE1", "FE2", "FE3", "FE4", "FE5", "FE6", "FE7", "FE8", "FE9", "FE10", "FE11", "FE12", "FE13", "FE14", "FE15", "FE16", "FEH", "FEW"], 103),
    new animeInfo("My Neighbor Totoro", ["Tonari no Totoro", "MNT", "My Neighbour Totoro", "Totoro"], 104),
    new animeInfo("Rakudai Kishi no Cavalry", ["Chivalry of a Failed Knight", "A Tale of Worst One", "Rakudai"], 105),
    new animeInfo("Tower of God", ["ToG", "Kami no Tou"], 106),
    new animeInfo("Dr. Stone", ['Dcst', 'DrS', 'Dr Stone'], 107),
    new animeInfo("The God of High School", ['The God of Highschool', 'GoH', 'Lisenin Tanrisi'], 108),
    new animeInfo("ID: INVADED", ['ID:INVADED', 'ID Invaded'], 109),
    new animeInfo("91 Days", [], 110),
    new animeInfo("Death March kara Hajimaru Isekai Kyousoukyoku", ['Death March to The Parallel World Rhapsody', 'Death Marching to the Parallel World Rhapsody', 'Death March', 'Deathma', 'Desumachi'], 111),
    new animeInfo("Blue Period", ['Periodo Azul', 'BLP'], 112),
    new animeInfo("Banana Fish", ['BF'], 113),
    new animeInfo("Black Bullet", [], 114),
    new animeInfo("Gakusen Toshi Asterisk", ["The Asterisk War", "Asterisk"], 115),
    new animeInfo("Blue Exorcist", ['Ao no Futsumashi', 'Ao no Exorcist', 'AnE', 'BE', 'AoEx'], 116),
    new animeInfo("Assassin's Pride", ["Assassins Pride"], 117),
    new animeInfo("Monster", [], 118),
    new animeInfo("Platinum End", [], 119),
    new animeInfo("The Gamer", [], 120),
    new animeInfo("Hoshiai no Sora", ['Star-Crossing Skies', 'Hoshiai no Soraw', 'HnS'], 121),
    new animeInfo("UnderPrin", [], 122),
    new animeInfo("No Guns Life", ['The Way of Life of a Man Loading a Magazine'], 123),
    new animeInfo("Doom Breaker", ['Reincarnation of the Suicidal Battle God'], 124),
    new animeInfo("Omniscient Reader", ["Omniscient Reader's Viewpoint", "ORV", "Punkt Widzenia Wszechwiedzacego Czytelnika", "Lecteur Omniscient", "Punkt Widzenia Wszechwiedzącego Czytelnika"], 125),
    new animeInfo("Martial Peak", ['The Pinnacle of Martial Arts', 'Wu Lian Dian Feng'], 126),
    new animeInfo("Hajime no Ippo", ['The First Step', 'Fighting Spirit', 'HnI', 'Ippo'], 127),
    new animeInfo("Mondaiji-tachi ga Isekai Kara Kuru Sou Desu yo?", ["Mondaiji", "Mondaiji-tachi", "Problem Children Are Coming from Another World", "Aren't They?"], 128),
    new animeInfo("Berserk", [], 129),
    new animeInfo("Run with the Wind", ['KazeTsuyo', 'Kaze ga Tsuyoku Fuiteiru', 'Kaze ga Tsuyoku Fuite Iru'], 130),
    new animeInfo("Isekai wa Smartphone to Tomo ni.", ['IseSuma', 'In Another World With My Smartphone', 'IwS', 'Isekai Smartphone'], 131),
    new animeInfo("Nisekoi", ['Nisekoi: False Love'], 132),
    new animeInfo("Log Horizon", ['LH'], 133),
    new animeInfo("Kumo Desu ga, Nani ka?", ["So I'm a Spider, So What?", 'KDN', 'KDgNk', 'Kumodesuga', 'Kumo Desu ga'], 134),
    new animeInfo("Big Windup!", ['Oofuri', 'Ohkiku Furikabutte', 'Swing Big!', 'Swing Big', 'Big Windup', 'Ookiku Furikabutte'], 135),
    new animeInfo("Madan no Ou to Vanadis", ['The King of the Magic Bullet and Vanadis', 'Lord Marksman and Vanadis'], 136),
    new animeInfo("Tokyo Ghoul", ['Tokyo Kushu', 'TG', 'Tokyou Ghoul:re', 'Tokyo Ghoul√A', 'Tokyo Ghoul Root A'], 137),
    new animeInfo("Heavenly Demon Reborn!", ['Chronicles of Heavenly Demon', 'Heavenly Demon Reborn'], 138),
    new animeInfo("Tomb Raider King", ['Tomb Raider', 'Dogurwang', 'King of the Sword', 'King of Excavation', 'Raja Penjarah Makam', 'Dogulwang'], 139),
    new animeInfo("Ranking of Kings", ['King Ranking', 'Ousama Ranking', 'RoK'], 140),
    new animeInfo("Daily Lives of High School Boys", ['Nichibros', 'Danshi Koukousei no Nichijou'], 141),
    new animeInfo("Black Clover", ['BC'], 142),
    new animeInfo("The World's Finest Assassin Gets Reincarnated in Another World as an Aristocrat", ['Ansatsu Kizoku', 'Sekai Saikyou no Assassin, Isekai Kizoku ni Tensei Suru', "WFA", "Sekai Saikyou no Assassin", "The World's Finest Assassin", "The Worlds Finest Assassin", "World's Finest Assassin", "Worlds Finest Assassin", "Finest Assassin", "The Worlds Finest Assassin Gets Reincarnated in Another World as an Aristocrat"], 143),
    new animeInfo("【Oshi no Ko】", ['Favorite Girl', "My Idol's Child", 'Oshi no Ko', 'OnK'], 144),
    new animeInfo("The Eminence in Shadow", ['To Be a Power in the Shadows!', 'Kage no Jitsuryokusha ni Naritakute!', 'Kage no Jitsuryokusha ni Naritakute', 'To Be a Power in the Shadows', 'Shadow Garden'], 145),
    new animeInfo("Sweet Home", ['Dulce Hogar'], 146),
    new animeInfo("Violet Evergarden", [], 147),
    new animeInfo("Spice and Wolf", ['Ookami to Koushinryou', 'Spice & Wolf', 'Spicy Wolf'], 148),
    new animeInfo("Re:Zero kara Hajimeru Isekai Seikatsu", ["Re:Zero", "Re Zero", "ReZero", "Re:Zero - Starting Life in Another World"], 149),
    new animeInfo("Choujin Koukousei-tachi wa Isekai demo Yoyuu de Ikinuku you desu!", ['Choyoyu', 'High School Prodigies Have It Easy Even In Another World', 'Super Human High Schoolers Are in Another World, But Seem to be Living in Comfort!', 'Chojin', 'The Super High Schoolers Affording to Live in Another World!'], 150),
    new animeInfo("Toilet-Bound Hanako-kun", ["Toilet Bound Hanako kun", "Jibaku Shounen Hanako-kun", "Jibaku Shounen Hanako kun", "Hanako"], 151),
    new animeInfo("Soul Eater", ['SE'], 152),
    new animeInfo("Komi Can't Communicate", ["Komi", "Komi-san", "Komi san", "Komi-san wa Comyushou desu.", "Komi-san wa Comyushou desu", "Komi-san wa Komyushou desu.", "Komi-san wa Komyushou desu"], 153),
    new animeInfo("Seraph of the End", ["Owari no Seraph", "Seraph", "OnS", "SotE"], 154),
    new animeInfo("Piano no Mori", ['Piano Forest', 'The Perfect World of Kai', 'Forest of Piano'], 155),
    new animeInfo("Seirei Gensouki", ['Seirei Gensouki: Spirit Chronicles', 'SGSC', 'Spirit Chronicles'], 156),
    new animeInfo("How a Realist Hero Rebuilt the Kingdom", ["A Realist's Kingdom Reform Chronicles", 'Genkoku', 'Genjitsu Shugi Yuusha no Oukoku Saikenki', 'Realist Hero'], 157),
    new animeInfo("Trinity Seven", ["T7", "7-nin no Mahoutsukai", "7 nin no Mahoutsukai"], 158),
    new animeInfo("Nausicaä of the Valley of the Wind", ['Nausicaa of the Valley of the Wind', 'Kaze no Tani no Nausicaa', 'Kaze no Tani no Nausicaä', 'Nausicaä', 'Nausicaa'], 159),
    new animeInfo("Eromanga-sensei", ["Eromanga Sensei", "Eromanga", "Ero Manga Sensei"], 160),
    new animeInfo("Yosuga no Sora", ['Sky of Connection', 'In Solitude Where We are Least Alone', 'Yosuga'], 161),
    new animeInfo("Lalin's Curse", ["Lalin"], 162),
    new animeInfo("Arifureta Shokugyou de Sekai Saikyou", ["Arifureta", "Arifureta: From Commonplace to World's Strongest", "From Common Job Class to the Strongest in the World"], 163),
    new animeInfo("Food Fantasy", ["FoFa"], 164),
    new animeInfo("Onegai My Melody", ["My Melody"], 165),
    new animeInfo("Given", [], 166),
    new animeInfo("Your Throne", ["YT", "I Want To Be You, Just For A Day", "To Be You, Even Just For A Day", "Haruman Nega Doego Sipeo"], 167),
    new animeInfo("My Dress-Up Darling", ["My Dress Up Darling", "Dress-Up Darling", "My Dressup Darling", "Dressup Darling", "Dress Up Darling", "Sono Bisque Doll wa Koi wo Suru", "Bisque Doll", "Sono Kisekae Ningyou wa Koi wo Suru"], 168),
    new animeInfo("hololive", ["hololive Production", "hololive EN"], 169),
    new animeInfo("Kiss x Sis", ["KxS"], 170),
    new animeInfo("She Professed Herself Pupil of the Wise Man", ['KenDeshi', 'Kenja no Deshi wo Nanoru Kenja the Comic', 'Kenja no Deshi'], 171),
    new animeInfo("Jungle Juice", [], 172),
    new animeInfo("Roxana", ["The Way to Protect the Female Lead's Older Brother", "How to Protect the Heroine's Older Brother"], 173),
    new animeInfo("The Villainess Turns the Hourglass", ['The Villainess Reverses the Hourglass'], 174),
    new animeInfo("Suddenly I Became a Princess", ['Suddenly Became A Princess One Day ', 'One Day, I Became a Princess', 'Suddenly, I Became a Princess', 'Who Made Me a Princess'], 175),
    new animeInfo("The Remarried Empress", ['The Second Marriage', 'Remarried Empress'], 176),
    new animeInfo("Life With an Ordinary Guy Who Reincarnated Into a Total Fantasy Knockout", ['Fantasy Knockout', 'Fabiniku', 'Isekai Bishoujo Juniku Ojisan to', 'Isekai Bishoujo Juniku Ojisan'], 177),
    new animeInfo("SSS-Class Revival Hunter", ['SSS-Class Suicide Hunter', 'SSS Class Revival Hunter', 'SSS Class Suicide Hunter'], 178),
    new animeInfo("Volcanic Age", ['Mount Hua Reincarnation', 'Hwasanjeonsaeng'], 179),
    new animeInfo("Rosario to Vampire", ['Rosario and Vampire', 'Rosario + Vampire'], 180),
    new animeInfo("86 -Eighty Six-", ['86', 'Eighty Six', 'Eighty-Six'], 181),
    new animeInfo("My Kingdom", ['Silent War'], 182),
    new animeInfo("Charlotte and Her 5 Disciples", ['Charlotte Has Five Disciples'], 183),
    new animeInfo("Anohana: The Flower We Saw That Day", ['AnoHana', "We Still Don't Know the Name of the Flower We Saw That Day.", "We Still Don't Know the Name of the Flower We Saw That Day", 'Anohana The Flower We Saw That Day', 'Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai', 'Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai.', 'Ano Hana'], 184),
    new animeInfo("Mekakucity Actors", ['Kagerou Days', "Mekakucity", 'Heat-Haze Days', 'Mekaku City Actors', 'Kagerou Project', 'Heat Haze Days', 'Kagerou Daze'], 185),
    new animeInfo("Vanitas no Carte", ['Vanitas no Karte', 'The Case Study of Vanitas', 'Vanitas'], 186),
    new animeInfo("Solitary Lady", ['Untouchable Lady'], 187),
    new animeInfo("The Genius Prince's Guide to Raising a Nation Out of Debt", ['Genius Prince', 'Tensai Ouji', 'Tensai Ouji no Akaji Kokka Saisei Jutsu'], 188),
    new animeInfo("Elfen Lied", ['EL'], 189),
    new animeInfo("Btooom!", ['Btooom', 'Btoom', 'Btom', 'Btoom!'], 190),
    new animeInfo("Super HxEros", ['Dokyuu Hentai HxEros', 'HxEros'], 191),
    new animeInfo("Isekai de Cheat Skill wo Te ni Shita Ore wa, Genjitsu Sekai wo mo Musou Suru: Level Up wa Jinsei wo Kaeta", ['I Got a Cheat Ability in a Different World, and Became Extraordinary Even in the Real World', 'Isekai de Cheat Nouryoku Ote ni Shita Ore wa, Genjitsu Sekai o mo Musou Suru', "Isekai de Cheat Skill", "Isekai Cheat Skill"], 192),
    new animeInfo("Shuumatsu Nani Shitemasu ka? Isogashii Desu ka? Sukutte Moratte Ii Desu ka?", ["SukaSuka", "WorldEnd", "Shuumatsu Nani Shitemasu ka?", "WorldEnd: What Do You Do at the End of the World? Are You Busy? Will You Save Us?", "Shuumatsu Nani Shitemasu ka? Mou Ichido dake", "Aemasu ka?", "What Do You Do at the End of the World? May I Meet You", "Once Again?", "SukaMoka"], 193),
    new animeInfo("Ya Boy Kongming!", ['Party People Kongming', 'Paripi Kongming', 'Kongming', 'Paripi Koumei', 'Party People Koumei', 'Koumei'], 194),
    new animeInfo("SPY x FAMILY", ['SxF', 'Spy Family', 'SPYxFAMILY'], 195),
    new animeInfo("Shikimori's Not Just a Cutie", ['Shikimori is Not Just a Cutie', "That Girl Isn't Just Cute", 'That Girl Is Not Just Cute', 'Kawaii Dake janai Onnanoko', 'Kawaii dake ja Nai Shikimori-san'], 196),
    new animeInfo("Aharen-san wa Hakarenai", ['Aharen Is Indecipherable', 'Aharen Is Unfathomable'], 197),
    new animeInfo("A Couple of Cuckoos", ['Kakkou no Iinazuke', "The Cuckoo's Fiancee"], 198),
    new animeInfo("I'm Quitting Heroing", ['Yamemasu Tsugi No Shokuba Ha Mao Jo', 'yuuyame', "I'm Quitting Heroing: Next Gig Is at the Demon Queen's Castle", 'Yuusha, Yamemasu', "YY"], 199),
    new animeInfo("Deor", [], 200),
    new animeInfo("Love After World Domination", ['Koi wa Sekai Seifuku no Ato de'], 201),
    new animeInfo("The Greatest Demon Lord Is Reborn as a Typical Nobody", ['Shijou Saikyou no Daimaou, Murabito A ni Tensei suru', 'SSnD', 'The Greatest Maou Is Reborned To Get Friends'], 202),
    new animeInfo("Skeleton Knight in Another World", ['Gaikotsu Kishi-sama, Tadaima Isekai e Odekakechu', 'Skeleton Knight'], 203),
    new animeInfo("Detective Conan", ['Case Closed', 'Conan', 'Meitantei Conan'], 204),
    new animeInfo("Ryoushin no Shakkin wo Katagawari Shite Morau Jouken wa Nihonichi Kawaii Joshikousei to Issho ni Kurasu Koto deshita.", ["I'm Gonna Live with You Not Because My Parents Left Me Their Debt But Because I Like You"], 205),
    new animeInfo("Inuyashiki", ['Inuyashiki Last Hero'], 206),
    new animeInfo("Second Life Ranker", ['The Ranker Who Lives Twice', 'Ranker Who Lives a Second Time'], 207),
    new animeInfo("Warau Arsnotoria Sun!", ['Smile of the Arsnotoria the Animation', 'Smile of the Arsnotoria', 'Warau Arsnotoria Sun'], 208),
    new animeInfo("The Strongest Sage with the Weakest Crest", ['Shikkakumon no Saikyou Kenja'], 209),
    new animeInfo("Akebi's Sailor Uniform", ['Akebi-chan no Serafuku', "Akebi's School Uniform"], 210),
    new animeInfo("Fairy Tail", ['FT'], 211),
    new animeInfo("Kunoichi Tsubaki no Mune no Uchi", ["Inside Tsubaki Kunoichi's Heart", "Kunoichi Tsubaki", 'In The Heart of Kunoichi Tsubaki'], 212),
    new animeInfo("Classroom of the Elite", ['Youjitsu', 'You-Zitsu', 'Youzitsu', 'CotE', 'Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e'], 213),
    new animeInfo("Sasaki and Miyano", ['Sasaki to Miyano'], 214),
    new animeInfo("Hunter x Hunter", ['HxH', 'HUNTER×HUNTER'], 215),
    new animeInfo("Ascendance of a Bookworm", ["Ascendance of a Bookworm: I'll do anything to become a librarian", 'Honzuki no Gekokujou', 'Honzuki no Gekokujou: Shisho ni Naru Tame ni wa Shudan wo Erandeiraremasen'], 216),
    new animeInfo("One Punch Man", ['OPM', 'One-Punch Man'], 217),
    new animeInfo("Bleach", [], 218),
    new animeInfo("Vermeil in Gold", ['Kinsou no Vermeil'], 219),
    new animeInfo("My Senpai is Annoying", ['Senpai ga Uzai Kouhai no Hanashi'], 220),
    new animeInfo("Hinako Note", [], 221),
    new animeInfo("Mahou Shoujo Madoka★Magica", ['Mahou Shoujo Madoka Magika', 'Magical Girl Madoka Magica', 'PMMM', 'MSMM', 'Puella Magi Madoka Magica', 'Madoka Magika'], 222),
    new animeInfo("Kamisama Kiss", ['Kamisama Hajimemashita', 'Kami-sama Kiss'], 223),
    new animeInfo("Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka", ['Danmachi', 'Is It Wrong to Try to Pick Up Girls in a Dungeon?', 'DanMachi: Familia Myth', 'Familia Myth'], 224),
    new animeInfo("The Idaten Deities Know Only Peace", ['Idaten Deities in the Peaceful Generation', 'Heion Sedai no Idatentachi', "HSI"], 225),
    new animeInfo("Kore wa Zombie Desu ka?", ['Is this a Zombie?', 'Korezom', 'KWZ'], 226),
    new animeInfo("ME!ME!ME!", ["MeMeMe", "Me Me Me", "MeMe", "Memes"], 227),
    new animeInfo("The Devil is a Part-Timer!", ['Hataraku Maou-sama!', 'HMs!'], 228),
    new animeInfo("Pop Team Epic", ['PPTP', 'PTE', 'Poputepipikku', 'Bob Epic Team', 'Bobunemimimmi'], 229),
    new animeInfo("Doki Doki Literature Club!", ["DDLC"], 230),
    new animeInfo("Mirai Nikki", ['The Future Diary', 'Future Diary'], 231),
    new animeInfo("The Garden of Words", ['The Garden of Kotonoha', 'Kotonoha no Niwa'], 232),
    new animeInfo("Black Summoner", ["Kuro no Shoukanshi", "The Berserker Rises to Greatness"], 233),
    new animeInfo("Parasyte", ['Kiseijuu', 'Parasyte - the maxim-', 'Parasyte: The Maxim', 'Kiseijuu: Sei no Kakuritsu'], 234),
    new animeInfo("Rikei ga Koi ni Ochita no de Shoumei shitemita", ['RikeKoi', 'Science Fell in Love, So I Tried to Prove It', 'Science Fell in Love'], 235),
    new animeInfo("Steins;Gate", ['S;G', 'SG', 'S;G 0', 'Steins;Gate 0', 'Steins Gate', 'Steins Gate 0', 'SG 0'], 236),
    new animeInfo("Cyberpunk", ["Cyberpunk: Edgerunners", 'Cyberpunk Edgerunners', 'CPE', 'Edgerunners'], 237),
    new animeInfo("Bungou Stray Dogs", ['BSD', 'Bungo Stray Dogs', 'Literary Stray Dogs'], 238),
    new animeInfo("Zetsuen no Tempest", ['Zetsuen no Tempest: The Civilization Blaster', 'Blast of Tempest'], 239),
    new animeInfo("Beelzebub", [], 240),
    new animeInfo("Tokyo Mirage Sessions ♯FE", ["Tokyo Mirage Sessions FE", "TMS", "Shin Megami Tensei X Fire Emblem", "Tokyo Mirage Sessions", "Tokyo Mirage Sessions #FE"], 241),
    new animeInfo("Camelot Series", ["Camelot", "Camelot OC", "Detective Jessy"], 242),
    new animeInfo("Chainsaw Man", ["CSM"], 243),
    new animeInfo("Dragon Ball", ['Dragonball', 'DB', 'Dragon Ball Z', 'Dragonball Z', 'Dragon Ball Super', 'Dragonball Super', 'Dragonball GT', 'Dragon Ball GT'], 244),
    new animeInfo("Ani ni Tsukeru Kusuri wa Nai!", ["Please Take My Brother Away"], 245),
    new animeInfo("Menhera Shoujo Kurumi-chan", ["Menhera-chan", "Unstable Girl Kurumi-chan", "Crazy Girl Kurumi-chan"], 246),
    new animeInfo("Majo to Ryouken", ["Witch and Hound"], 247),
    new animeInfo("Domestic Girlfriend", ['DomeKano', 'DomGF', 'Domestic na Kanojo'], 248),
    new animeInfo("Gintama", ['Gin Tama', 'Silver Soul', 'Yorinuki Gintama-san'], 249),
    new animeInfo("Isekai Ojisan", ['Ojisan in Another World', 'Isekai Uncle', 'IO', 'Uncle in Another World'], 250),
    new animeInfo("Tensei Kenja no Isekai Life", ["My Isekai Life: I Gained a Second Character Class and Became the Strongest Sage in the World!", 'Tensei Kenja no Isekai Life: Dai-2 no Shokugyou wo Ete, Sekai Saikyou ni Narimashita'], 251),
    new animeInfo("Naruto", ['Naruto Shippuden'], 252),
    new animeInfo("5 Centimeters per Second", ['Five Centimeters Per Second', 'Byousoku 5 Centimeter - a chain of short stories about their distance', '5 cm per second', 'Byousoku 5 Centimeter'], 253),
    new animeInfo("Parallel World Pharmacy", ['Isekai Yakkyoku'], 254),
    new animeInfo("ORIENT", [], 255),
    new animeInfo("SHADOWS HOUSE", ['Shadow House'], 256),
    new animeInfo("The Maid I Hired Recently is Mysterious", ['Saikin Yatotta Maid ga Ayashii', 'SYMA'], 257),
    new animeInfo("Soredemo Ayumu wa Yosetekuru", ['Even so, Ayumu draws closer to the endgame', 'When Will Ayumu Make His Move?', 'SoreAyu', 'SawY'], 258),
    new animeInfo("The Yakuza's Guide to Babysitting", ['Kumichou Musume to Sewagakari'], 259),
    new animeInfo("Harem in the Labyrinth of Another World", ['Isekai Meikyuu de Harem wo', 'IMH'], 260),
    new animeInfo("My Stepmom's Daughter is My Ex", ['Tsurekano', 'My Stepsister is My Ex-Girlfriend', 'Step-Exes', 'Mamahaha no Tsurego ga Motokano datta'], 261),
    new animeInfo("Yuuna and the Haunted Hot Springs", ['Yuragisou no Yuuna-san', 'Yuuna of Yuragi Manor', 'YnY'], 262),
    new animeInfo("Hyouka", ['Classic Literature Club Series'], 263),
    new animeInfo("Do You Love Your Mom and Her Two-Hit Multi-Target Attacks?", ['Do You Like Your Mom? Her Normal Attack is Two Attacks at Full Power', 'Tsuujou Kougeki ga Zentai Kougeki de 2-kai Kougeki no Okaasan wa Suki desu ka?', 'twohitmom', 'TK', 'OO', 'Tsujou Kogeki'], 264),
    new animeInfo("Fire Force", ['Enen no Shouboutai', 'Fire Brigade of Flames', 'EnS'], 265),
    new animeInfo("Kengan Ashura", ['Kengan Asura'], 266),
    new animeInfo("Howl's Moving Castle", ['Hauru no Ugoku Shiro'], 267),
    new animeInfo("Call of the Night", ['Song of the Night Walkers', 'Night Owl Song', 'Yofukashi no Uta', 'YnU', 'CotN'], 268),
    new animeInfo("Plastic Memories", ['Plamemo'], 269),
    new animeInfo("Lycoris Recoil", ['LycoRyco', 'LycoReco'], 270),
    new animeInfo("Beatless", ['Beatless Final Stage'], 271),
    new animeInfo("My Hero Academia", ['BNHA', 'MHA', 'Boku no Hero Academia', 'HeroAca'], 272),
    new animeInfo("I'm the Villainess, So I'm Taming the Final Boss", ['Akuyaku Reijo Nanode Rasubosu o Katte Mimashita', 'Villainous Daughter Aims for the Last Boss', "I'm a Villainous Daughter, so I'm Going to Keep the Last Boss", "I'm the Villainous Daughter, So I'm Keeping the Last Boss", 'Akuyaku Reijou nanode Last Boss wo Kattemimashita', 'AkuLas'], 273),
    new animeInfo("Wandering Witch: The Journey of Elaina", ['MajoTabi', 'Majo no Tabitabi', 'The Journey of Elaina', 'Wandering Witch'], 274),
    new animeInfo("Miss Kobayashi's Dragon Maid", ['Kobayashi-san Chi no Maid Dragon', 'Maidragon', 'The Maid Dragon of Kobayashi-san', 'Maid Dragon', 'Dragon Maid', "Kobayashi san's Dragon Maid", "Kobayashi-san's Dragon Maid"], 275),
    new animeInfo("Otonari no Tenshi-sama ni Itsunomanika Dame Ningen ni Sareteita Ken", ["The Angel Next Door Spoils Me Rotten", "Angel Next Door"], 276),
    new animeInfo("The Seven Deadly Sins", ['7 Deadly Sins', 'SDS', '7DS', 'NnT', 'Nanatsu no Taizai'], 277),
    new animeInfo("Boruto", ["Boruto: Naruto Next Generations"], 278),
    new animeInfo("Tanaka-kun is Always Listless", [], 279),
    new animeInfo("Eleceed", [], 280),
    new animeInfo("Overflow", ["Iretara Afureru Shimai no Kimochi", "Jitsu wa Ima Haittemasu....: Ofuro de Onii-chan no Katai Are ga...", "My Brother's Slipped Inside Me in The Bathtub"], 281),
    new animeInfo("Itadaki! Seieki♥", ["Itadaki Seieki", "Vampire Vixen", "Gimme That Semen!"], 282),
    new animeInfo("Medaka Box", [], 283),
    new animeInfo("Farming Life in Another World", ['Isekai Nonbiri Nouka'], 284),
    new animeInfo("Assassination Classroom", ['Ansatsu Kyoushitsu', 'Ansatsu Kyoshitsu', 'Ass Class', 'AssClass', 'AC'], 285),
    new animeInfo("The Detective Is Already Dead", ['Tanmoshi', 'Tantei wa Mou, Shindeiru', 'TDAD', 'Tantei wa Mou Shindeiru'], 286),
    new animeInfo("Bocchi the Rock!", ['BtR', 'Bocchi the Rock', 'Bocchi', 'Bozaro'], 287),
    new animeInfo("The Misfit of Demon King Academy", ['Maou Gakuin no Futekigousha', 'Misfit of Demon King Academy'], 288),
    new animeInfo("Princess Mononoke", [], 289),
    new animeInfo("Kiki's Delivery Service", ['Majo no Takkyuubin', 'Majotaku'], 290),
    new animeInfo("Ponyo", ['Ponyo on the Cliff by the Sea'], 291),
    new animeInfo("Castle in the Sky", ['Tenkuu no Shiro Rapyuta', 'Tenkuu no Shiro Laputa', 'Laputa'], 292),
    new animeInfo("Whisper of the Heart", ['If You Listen Carefully'], 293),
    new animeInfo("The Secret World of Arrietty", ['Karigurashi no Arrietti', 'The Borrower Arrietty'], 294),
    new animeInfo("Charlotte", [], 295),
    new animeInfo("The Wind Rises", ['Kaze Tachinu'], 296),
    new animeInfo("Fullmetal Alchemist", ['Full Metal Alchemist', 'FMA', 'Fullmetal Alchemist: Brotherhood', 'Full Metal Alchemist: Brotherhood', 'FMAB'], 297),
    new animeInfo("Date A Live", ['Date A Bullet'], 298),
    new animeInfo("Secret Class", [], 299),
    new animeInfo("Reborn to Master the Blade", ['Eiyuuou, Bu wo Kiwameru Tame Tenseisu', 'Reborn to Master the Blade: From Hero-King to Extraordinary Squire'], 300),
    new animeInfo("Tomo-chan Is a Girl!", ['Tomo-chan wa Onna no ko!'], 301),
    new animeInfo("Absolute Duo", [], 302),
    new animeInfo("Erased", ['Bokumachi', 'Boku dake ga Inai Machi', 'The Town Where Only I am Missing'], 303),
    new animeInfo("Goblin Slayer", [], 304),
    new animeInfo("Blue Lock", ['BLLK', 'BLUELOCK'], 305),
    new animeInfo("Danganronpa", ['DR', 'Danganronpa Series', 'DGRP'], 306),
    new animeInfo("Love Live!", ['Love Live! Series', 'Love Live', 'LL!', 'LL'], 307),
    new animeInfo("Baki", ['Baki the Grappler', 'Grappler Baki'], 308),
    new animeInfo("Sailor Moon", ['Pretty Soldier Sailor Moon', 'Pretty Guardian Sailor Moon', 'Bishoujo Senshi Sailor Moon', 'PSSM', 'BSSM', 'SM'], 309),
    new animeInfo("NieR", ["NieR Automata", "NieR: Automata", "NieR:A", "NieRA", "N:A"], 310),
    new animeInfo("Cross Ange", ['Cross Ange: Rondo of Angel and Dragon', 'CA'], 311),
    new animeInfo("The Beginning After the End", ["TBATE"], 312),
    new animeInfo("Lookism", ['Gaiken Shijou Shugi'], 313),
    new animeInfo("K-On!", ['Keion', 'K on', 'K-on', 'K-On!!'], 314),
    new animeInfo("Welcome to Japan, Ms. Elf!", ['Welcome to Japan, Elf-san'], 315),
    new animeInfo("My Wife Is From a Thousand Years Ago", ['Wo Jia Laopo Lai Zi Yiqian Nian Qian'], 316),
    new animeInfo("Oni Chichi", [], 317),
    new animeInfo("Netoge no Yome wa Onnanoko ja Nai to Omotta?", ['And you thought there is never a girl online?', 'Netoge no Yome', 'NetoYome'], 318),
    new animeInfo("The Irregular at Magic High School", ['Mahouka Koukou no Rettousei', 'MKNR', 'Mahouka', 'The Honor Student at Magic High School'], 319),
    new animeInfo("Mob Psycho 100", ['MP100', 'Mob'], 320),
    new animeInfo("Tengen Toppa Gurren Lagann", ['TTGL', 'Gurren Lagann'], 321),
    new animeInfo("Toaru", ['Toaru Majutsu no Index', 'Toaru Kagaku no Railgun', 'Toaru Kagaku no Accelerator', 'A Certain Magical Index', 'A Certain Scientific Railgun', 'A Certain Scientific Accelerator', 'Raildex'], 322),
    new animeInfo("Darwin's Game", ['D-Game', 'Darwins Game'], 323),
    new animeInfo("Kiznaiver", [], 324),
    new animeInfo("How Heavy Are the Dumbbells You Lift?", ['Dumbbell Nan Kilo Moteru'], 325),
    new animeInfo("The Saint's Magic Power is Omnipotent", ['The power of the saint is all around'], 326),
    new animeInfo("Fugou Keiji", ['Fugou Keiji: Balance:UNLIMITED', 'The Millionaire Detective', 'The Millionaire Detective - Balance: UNLIMITED'], 327),
    new animeInfo("Hellsing", ['Hellsing Ultimate'], 328),
    new animeInfo("Tokyo Revengers", ['Toman', 'TR', 'TokRev'], 329),
    new animeInfo("Akashic Records of Bastard Magic Instructor", ['RokuAka', 'Rokudenashi Majutsu Koushi to Akashic Records', 'RMKtAR', 'Rokudenashi Majutsu Koushi to Kinki Kyouten'], 330),
    new animeInfo("The King's Avatar", ["King's Avatar", 'Quanzhi Gaoshou', 'TKA', 'QZGS', 'QG'], 331),
    new animeInfo("Kyoukai no Kanata", ['Beyond the Boundary', 'Kyokai no Kanata', 'Kyokai'], 332),
    new animeInfo("Uzaki-chan Wants to Hang Out!", ['Uzaki-chan wa Asobitai!', 'Uzaki-chan wa Asobitai', 'Uzaki-chan', 'Uzaki'], 333),
    new animeInfo("Blend S", ['Blend-S'], 334),
    new animeInfo("Higurashi: When They Cry", ['When the Cicadas Cry', 'Higurashi', 'Higurashi no Naku Koro ni', 'When the Evening Cicadas Cry'], 335),
    new animeInfo("Akatsuki no Yona", ['AkaYona', 'Yona of the Dawn', 'AnY', 'YotD'], 336),
    new animeInfo("Deadman Wonderland", ['DMWL'], 337),
    new animeInfo("SSSS.Gridman", ['SSSS Gridman', 'Gridman'], 338),
    new animeInfo("SSSS.Dynazenon", ['SSSS Dynazenon', 'Dynazenon'], 339),
    new animeInfo("Trigun", ['Trigun Stampede'], 340),
    new animeInfo("Darker than Black", ['DtB'], 341),
    new animeInfo("Welcome to Demon School! Iruma-kun", ["Iruma-kun!", 'Welcome to Demon School, Iruma-kun!', 'Mairimashita! Iruma-kun', 'Mairuma', 'Mairimashita Iruma-kun', 'Welcome to Demon School Iruma-kun'], 342),
    new animeInfo("Honkai: Star Rail", ["Honkai Star Rail", "HSR", "Star Rail"], 343),
    new animeInfo("Cowboy Bebop", ['CB', "Cowboy Bebop: Knockin' on Heaven's Door"], 344),
    new animeInfo("JoJo's Bizarre Adventure", ['JoJos Bizarre Adventure', 'Jojo no Kimyou na Bouken', 'JJBA', 'Jojo'], 345),
    new animeInfo("RWBY", ['RWBY: Ice Queendom', 'RWBY: Hyousetsu Teikoku'], 346),
    new animeInfo("Food Wars!", ['Shokugeki no Souma', 'SnS', 'Shokugeki no Soma', 'Food Wars'], 347),
    new animeInfo("Accel World", ['Accelerated World', 'AW'], 348),
    new animeInfo("The Ancient Magus' Bride", ['The Ancient Magus Bride', 'Mahoutsukai no Yome', "The Magician's Bride", 'Mahoyome', 'MnY', 'TAMB'], 349),
    new animeInfo("Summer Time Rendering", ['Summertime Render', 'Summer Time Render', 'Summertime Rendering', 'STR'], 350),
    new animeInfo("The Ice Guy and His Cool Female Colleague", ['Koori Zokusei Danshi to Cool na Douryou Joshi', 'Koori Zokusei Danshi to Kuuruna Douryou Joshi', 'Ice Guy and the Cool Female Colleague', 'Ice Cool', 'ICPC'], 351),
    new animeInfo("Koi to Uso", ['Love and Lies', 'KtU'], 352),
    new animeInfo("Made in Abyss", [], 353),
    new animeInfo("Battle Game in 5 Seconds", ['Battle in 5 seconds after meeting.', 'Deatte 5-byou de Battle'], 354),
    new animeInfo("The Legend of Heroes: Trails in the Sky", ["Trails in the Sky", "Legend of the Heroes: Trails in the Sky", 'Eiyuu Densetsu: Sora no Kiseki'], 355),
    new animeInfo("Revue Starlight", ["Girls' Musical Revue Starlight", 'Shoujo☆Kageki Revue Starlight'], 356),
    new animeInfo("Clannad", [], 357),
    new animeInfo("The Melancholy of Haruhi Suzumiya", ['Suzumiya Haruhi no Yuuutsu', 'Haruhi Suzumiya no Yuuutsu', 'TMoHS', 'SHnY'], 358),
    new animeInfo("Fruits Basket", ['Furuba', 'Fruba', 'FB'], 359),
    new animeInfo("Pandora Hearts", ['PanHearts', 'PH'], 360),
    new animeInfo("Katekyo Hitman Reborn!", ['Reborn!', 'KHR', 'Reborn'], 361),
    new animeInfo("Record of Ragnarok", ['Shuumatsu no Valkyrie', 'RoR', 'Shumatsu no Valkyrie'], 362),
    new animeInfo("Devil May Cry", ['DMC'], 363),
    new animeInfo("My Love Story with Yamada-kun at Lv999", ['Loving Yamada at LV999!', 'My Lv999 Love for Yamada-kun', 'Yamada-kun to Lv999 no Koi wo Suru', 'Going through a Lv999 Love with Yamada-kun'], 364),
    new animeInfo("A Place Further Than the Universe", ['Sora yorimo Tooi Basho', 'Yorimoi', 'APFTTU'], 365),
    new animeInfo("Black Lagoon", [], 366),
    new animeInfo("God Eater", ['GE', 'Gods Eater'], 367),
    new animeInfo("Spy Classroom", ['Spy Room', 'Spy Kyoushitsu'], 368),
    new animeInfo("Honkai Impact 3rd", ["Houkai 3rd", "HI3", "Honkai Impact 3"], 369),
    new animeInfo("K", ['K-Project', 'K Project', 'K Return of Kings'], 370),
    new animeInfo("Houseki no Kuni", ['Land of the Lustrous', 'Kingdom of Gems', 'HnK', 'LotL'], 371),
    new animeInfo("Akudama Drive", ['AD'], 372),
    new animeInfo("Black Butler", ['Kuroshitsuji', 'BB'], 373),
    new animeInfo("Infinite Stratos", ['IS'], 374),
    new animeInfo("The Greatest Estate Developer", ["TGED"], 375),
    new animeInfo("My Blasted Reincarnated Life", ["Damn Reincarnation"], 376),
    new animeInfo("Why Raeliana Ended Up at the Duke's Mansion", ["The Reason Why Raeliana Ended up at the Duke's Mansion", 'Why She Had to Go to the Duke', "The Duke's Fiancée", "The Duke's Fiancee", 'TDF', 'Raeliana'], 377),
    new animeInfo("Saint Seiya", ['Knights of the Zodiac', 'KotZ'], 378),
    new animeInfo("Wolf's Rain", ['Wolf Rain', 'Wolfs Rain', 'WR'], 379),
    new animeInfo("Monogatari Series", ['Monogatari', 'Bakemonogatari', 'Kizumonogatari', 'Nisemonogatari', 'Nekomonogatari', 'Kabukimonogatari', 'Hanamonogatari', 'Otorimonogatari', 'Onimonogatari', 'Koimonogatari', 'Tsukimonogatari', 'Koyomimonogatari', 'Owarimonogatari'], 380),
    new animeInfo("The Daily Life of the Immortal King", ["Fairy King's Daily Life", 'Life of Immortal King', 'Xian Wang de Richang Shenghou', 'TDLoTIK'], 381),
    new animeInfo("The Furious Yama", ['Dawang Bu Gaoxing'], 382),
    new animeInfo("Claymore", [], 383),
    new animeInfo("Vampire Knight", ['VK'], 384),
    new animeInfo("BanG Dream!", ['Bandori', 'BanG Dream! Girls Band Party!', 'Bandori Garupa', 'Garupa'], 385),
    new animeInfo("The Disastrous Life of Saiki K.", ['Saiki Kusou no Psi Nan', 'Saiki Kusou'], 386),
    new animeInfo("Little Witch Academia", ['LWA'], 387),
    new animeInfo("Vagabond", [], 388),
    new animeInfo("Rokka no Yuusha", ['Rokka: Braves of the Six Flowers', 'RnY'], 389),
    new animeInfo("To LOVE-Ru", ['To-LOVE-Ru', 'To Love Ru', 'TLR', 'To Loveru'], 390),
    new animeInfo("White Album 2", ['WA2', 'WA 2'], 391),
    new animeInfo("D.Gray-man", ['DGM', 'D Gray man', 'D. Gray-man'], 392),
    new animeInfo("Overgeared", ["OG"], 393),
    new animeInfo("Skip to Loafer", ['Skip and Loafer'], 394),
    new animeInfo("Outbreak Company", [], 395),
    new animeInfo("Plunderer", [], 396),
    new animeInfo("Our Last Crusade or the Rise of a New World", ['Kimisen', 'Kimi to Boku no Saigo no Senjou, Arui wa Sekai ga Hajimaru Seisen', 'Kimi to Boku no Saigo no Senjou', 'The War Ends the World / Raises the World'], 397),
    new animeInfo("Another", [], 398),
    new animeInfo("Brynhildr in the Darkness", ['Gokukoku no Brynhildr', 'GnB'], 399),
    new animeInfo("Free!", ['Free! - Iwatobi Swim Club'], 400),
    new animeInfo("Great Teacher Onizuka", ['GTO'], 401),
    new animeInfo("Love, Chunibyo & Other Delusions", ['Chuunibyou demo Koi ga Shitai!', 'Chu-2', 'Chuuni', 'LCaOD'], 402),
    new animeInfo("Dig Delight Direct Drive DJ", ['D4DJ', 'DDDDD', 'D4DJ First Mix', 'D4DJ All Mix', 'D4DJ Groovy Mix', 'D4DJ Petit Mix'], 403),
    new animeInfo("Tomodachi Game", ['Friends Game'], 404),
    new animeInfo("3-gatsu no Lion", ['Sangatsu no Lion', 'March comes in like a lion'], 405),
    new animeInfo("Classroom for Heroes", ['Eiyuu Kyoushitsu', 'Hero Classroom', 'Class Room✿For Heroes'], 406),
    new animeInfo("Liar, Liar", [], 407),
    new animeInfo("Am I Actually the Strongest?", ['Jitsu wa Ore, Saikyou Deshita?'], 408),
    new animeInfo("Bible Black", [], 409),
    new animeInfo("Imouto Paradise!", [], 410),
    new animeInfo("Maki-chan to Nau.", [], 411),
    new animeInfo("Uhou Renka", [], 412),
    new animeInfo("Goblin no Suana", [], 413),
    new animeInfo("Kitsune Musume no Ecchi na Oyado", ["Fox Girl's Naughty Inn"], 414),
    new animeInfo("Miss Shachiku and the Little Baby Ghost", ["SYYL", "Shachiku-san wa Youjo Yuurei ni Iyasaretai.", 'Ms. Corporate Slave Wants to be Healed by a Loli Spirit'], 415),
    new animeInfo("Nuki Doki! Tenshi to Akuma no Sakusei Battle", [], 416),
    new animeInfo("Oppai Heart: Kanojo wa Kedamono Hatsujouki!?", [], 417),
    new animeInfo("Baka na Imouto wo Rikou ni Suru no wa Ore no xx dake na Ken ni Tsuite", [], 418),
    new animeInfo("Mankitsu Happening", [], 419),
    new animeInfo("Eroge! H mo Game mo Kaihatsu Zanmai", ['Eroge! Sex & Game Make Sexy Games'], 420),
    new animeInfo("Ore ga Kanojo wo Okasu Wake", [], 421),
    new animeInfo("Euphoria", [], 422),
    new animeInfo("Kuroinu: Kedakaki Seijo wa Hakudaku ni Somaru", ['Black Dogs: Noble and Holy Women Tainted Milky White'], 423),
    new animeInfo("Gakuen de Jikan yo Tomare", ['Stop by Time at the School'], 424),
    new animeInfo("Koiito Kinenbi", ['Abrupt Holy Night', 'Holy Night Invader', 'Holy Night Happy Bell', 'Princess Fox'], 425),
    new animeInfo("Shinsei Futanari Idol: Dekatama Kei!", [], 426),
    new animeInfo("Yabai! Fukushuu Yami Site", [], 427),
    new animeInfo("Why the hell are you here, Teacher!?", ['Nande Koko ni Sensei ga!?'], 428),
    new animeInfo("Usamimi Bouken-tan: Sekuhara Shinagara Sekai wo Sukue", ['Rabbit Ear Chronicle'], 429),
    new animeInfo("HHH: Triple Ecchi", ['Triple Ecchi HHH'], 430),
    new animeInfo("Tropical KISS", [], 431),
    new animeInfo("Youkoso! Sukebe Elf no Mori e", ['Welcome! to the forest of lewd elves', 'Welcome! To The Slutty Elf Village'], 432),
    new animeInfo("Tensei Kendo no Harem Colosseum", ['Reborn Gladiator of the Baby-Making Colosseum: Harem Colosseum'], 433),
    new animeInfo("Oide yo! Mizuryuu Kei Land", ['Welcome to Mizuryuu Kei Land'], 434),
    new animeInfo("Bi-chiku Beach: Nangoku Nyuujoku Satsueikai", [], 435),
    new animeInfo("Kanojo x Kanojo x Kanojo", [], 436),
    new animeInfo("Tsugou no Yoi Sexfriend?", ['Sex Friends Convenience?'], 437),
    new animeInfo("Tamashii Insert", ['Soul Insert'], 438),
    new animeInfo("The Day I Became a God", ['Kamisama ni Natta Hi'], 439),
    new animeInfo("WataMote: No Matter How I Look At It, It's You Guys' Fault I'm Not Popular!", ['Watashi ga Motenai no wa Dou Kangaete mo Omaera ga Warui!', "It's Not My Fault That I'm Not Popular!", 'WataMote'], 440),
    new animeInfo("Bikini Warriors", [], 441),
    new animeInfo("Reign of the Seven Spellblades", ['Seven Magic Swords Rule', 'Nanatsuma', 'Nanatsu no Maken ga Shihai Suru'], 442),
    new animeInfo("The Seven Heavenly Virtues", ['Nanatsu no Bitoku'], 443),
    new animeInfo("Seven Mortal Sins", ['Sin: The 7 Deadly Sins', 'Sin: Nanatsu no Taizai'], 444),
    new animeInfo("The Promised Neverland", ['TPN', 'Promised Neverland', 'Yakusoku no Neverland'], 445),
    new animeInfo("MASHLE: MAGIC AND MUSCLES", ['Mashle'], 446),
    new animeInfo("The Faraway Paladin", ['Saihate no Paladin'], 447),
    new animeInfo("Sakamoto Days", [], 448),
    new animeInfo("Space Dandy", ['Space☆Dandy'], 449),
    new animeInfo("Space Brothers", ['Uchu Kyodai', 'Uchuu Kyoudai'], 450),
    new animeInfo("Dorohedoro", [], 451),
    new animeInfo("Among Us", ["Amogus", "Sus"], 452),
    new animeInfo("The 100 Girlfriends Who Really, Really, Really, Really, REALLY Love You", ['100 Kanojo', '100Kano', 'Hyakkano', '100 Girlfriends', 'Kimi no Koto ga Dai Dai Dai Dai Daisuki na 100-nin no Kanojo'], 453),
    new animeInfo("Ragna Crimson", [], 454),
    new animeInfo("Welcome to the N.H.K.", ['Welcome to the NHK', 'Welcome to the N-H-K', 'NHK ni Youkoso!'], 455),
    new animeInfo("Sunday Without God", ['The Sunday without God', 'Kami-Nai', 'Kaminai', 'Kamisama no Inai Nichiyoubi'], 456),
    new animeInfo("Frieren: Beyond Journey's End", ['Frieren at the Funeral', 'Sousou no Frieren'], 457),
    new animeInfo("Pumpkin Scissors", ['PumpSci'], 458),
    new animeInfo("Undead Unluck", [], 459),
    new animeInfo("Durarara!!", ['DRRR!!', 'Durarara', 'DRRR'], 460),
    new animeInfo("Shaman King", [], 461),
    new animeInfo("Re:CREATORS", ['Re Creators', 'Re CREATORS', 'RC'], 462),
    new animeInfo("GATE", ['Gate: Jieitai Kanochi nite, Kaku Tatakaeri', 'Gate: Thus the JSDF Fought There!'], 463),
    new animeInfo("Initial D", [], 464),
    new animeInfo("Berserk of Gluttony", ['Glutton Berserker ~The One That Exceeds The Concept Of Levels~', 'Boushoku no Berserk ~ Ore dake Level to Iu Gainen wo Toppa Suru ~', 'BoG', 'Boushoku no Berserk'], 465),
    new animeInfo("BEASTARS", ['BST'], 466),
    new animeInfo("Inazuma Eleven", ['IE'], 467),
    new animeInfo("Captain Tsubasa", ['Flash Kicker'], 468),
    new animeInfo("Girls und Panzer", ['Garupan', 'GuP', 'Girls & Panzer'], 469),
    new animeInfo("Banished from the Hero's Party, I Decided to Live a Quiet Life in the Countryside", ["Banished from the Heroes' Party, I Decided to Live a Quiet Life in the Countryside", "Banished from the brave man's group, I decided to lead a slow life in the back country.", "I Was Kicked out of the Hero's Party Because I Wasn't a True Companion so I Decided to Have a Slow Life at the Frontier", 'Shin no Nakama ja Nai to Yuusha no Party wo Oidasareta node, Henkyou de Slow Life suru Koto ni shimashita', 'Slow Life Frontier', 'Shin no Nakama', 'SnN'], 470),
    new animeInfo("Hell's Paradise", ["Hell's Paradise: Jigokuraku", 'Hells Paradise', 'HPJ', 'Jigokuraku', 'JGKRK'], 471),
    new animeInfo("7th Time Loop: The Villainess Enjoys a Carefree Life Married to Her Worst Enemy!", ['RupuNana', 'Loop7', 'Enemy Country in Her Seventh Loop'], 472),
    new animeInfo("TSUKIMICHI -Moonlit Fantasy-", ['Moon-led Journey Across Another World', 'Tsuki ga Michibiku Isekai Douchuu', 'TgM'], 473),
    new animeInfo("Tengoku Daimakyo", ['Heavenly Delusion'], 474),
    new animeInfo("Baccano!", ['B!'], 475),
    new animeInfo("Ron Kamonohashi's Forbidden Deductions", ['Ron Kamonohashi: Deranged Detective', 'Kamonohashi Ron no Kindan Suiri', 'Deranged Detective', 'RKFD'], 476),
    new animeInfo("Sleepy Princess in the Demon Castle", ['Maou Jou de Oyasumi', 'Maoujou de Oyasumi', 'MaouYasu', 'Sweet Dreams in the Demon Castle', 'MdO'], 477),
    new animeInfo("Irina: The Vampire Cosmonaut", ['The Moon, Laika, and Nosferatu', 'Tsuki to Laika to Nosferatu', 'TtLtN'], 478),
    new animeInfo("Versatile Mage", ['Quanzhi Fashi', 'Full-Time Magister'], 479),
    new animeInfo("Kabaneri of the Iron Fortress", ['Koutetsujou no Kabaneri', 'KotIF'], 480),
    new animeInfo("Reverse:1999", ["Reverse 1999", "R:1999", "R1999"], 481),
    new animeInfo("Isekai", [], 482),
    new animeInfo("Ghost in the Shell", ['GitS', 'Koukaku Kidoutai'], 483),
    new animeInfo("The Apothecary Diaries", ['Kusuriya no Hitorigoto', 'TAD'], 484),
    new animeInfo("Nichijou", ['Everyday', 'My Ordinary Life'], 485),
    new animeInfo("Campfire Cooking in Another World with my Absurd Skill", ['Regarding the Display of an Outrageous Skill Which Has Incredible Powers', 'Tondemo Skill de Isekai Hourou Meshi', 'TSdIHM'], 486),
    new animeInfo("Kaiju #8", ['Kaiju No. 8', 'Monster #8', 'Kaiju 8', 'K8'], 487),
    new animeInfo("Kaichou wa Maid-sama!", ['Maid Sama!', 'KwMs', 'Kaichou wa Maid Sama'], 488),
    new animeInfo("Strike the Blood", ['SutoBura', 'StB'], 489),
    new animeInfo("Wind Breaker", ['WB', 'WBK'], 490),
    new animeInfo("The Prince of Tennis", ['Tennis no Ouji-sama', 'Tenipuri', 'Tennis no Ouji sama', 'PoT'], 491),
    new animeInfo("Final Fantasy", ["FF", "Final Fantasy Series"], 492),
    new animeInfo("BURN ☩HE WITCH", ['BTW', 'Burn the Witch'], 493),
    new animeInfo("Diamond no Ace", ['Ace of Diamond', 'Daiya no Ace', 'Ace of the Diamond', 'Dia no A', 'DnA'], 494),
    new animeInfo("Slime Taoshite 300-nen", ["I've Been Killing Slimes for 300 Years and Maxed Out My Level", 'Slime Slayer', 'ST300', 'Slime300', 'While Killing Slimes for 300 Years, I Became the MAX Level Unknowingly'], 495),
    new animeInfo("Hibike! Euphonium", ['Hibike Euphonium', 'Sound Euphonium', 'Eupho', 'Sound! Euphonium'], 496),
    new animeInfo("Saint☆Young Men", ['Saint☆Oniisan', 'Saint Young Men', 'Saint Oniisan', 'SYM'], 497),
    new animeInfo("Karakuri Circus", ['Le Cirque de Karakuri'], 498),
    new animeInfo("Yuru Camp△", ['Laid-Back Camp', 'Yuru Camp', 'Yurucamp', 'Yurukyan', 'YC'], 499),
    new animeInfo("Kingdom", [], 500),
    new animeInfo("My New Boss is Goofy", ['Atarashii Joushi wa Do Tennen', 'My New Boss is a Natural Airhead'], 501),
    new animeInfo("Shangri-La Frontier", ['ShanFro', 'Shangri La Frontier'], 502),
    new animeInfo("Golden Kamuy", ['Golden Kamui', 'GK'], 503),
    new animeInfo("Dungeon Meshi", ['Delicious in Dungeon', 'DunMeshi'], 504),
    new animeInfo("The Dangers in My Heart", ['BokuYaba', 'Boku no Kokoro no Yabai Yatsu'], 505),
    new animeInfo("Zom 100: Bucket List of the Dead", ['Zom 100: Zombie ni Naru made ni Shitai 100 no Koto', 'Zombie 100'], 506),
    new animeInfo("Knights of Sidonia", ['Sidonia no Kishi'], 507),
    new animeInfo("Zero no Tsukaima", ["Zero's Familiar", 'The Familiar of Zero', 'ZnT'], 508),
    new animeInfo("Slam Dunk", ['SD'], 509),
    new animeInfo("InuYasha", ['Inu Yasha', 'IY'], 510),
    new animeInfo("Golden Time", [], 511),
    new animeInfo("A Sign of Affection", ['Yubisaki to Renren'], 512),
    new animeInfo("GO! GO! Loser Ranger!", ['Ranger Reject', 'Sentai Daishikkaku'], 513),
    new animeInfo("Aoashi", ['Ao Ashi', 'Blue Feet'], 514),
    new animeInfo("Touken Ranbu", ['Tourabu', 'TouRan', 'TKRB'], 515),
    new animeInfo("Bottom-Tier Character Tomozaki", ['Tomozaki-kun', 'Jaku-Chara Tomozaki-kun'], 516),
    new animeInfo("The Dreaming Boy is a Realist", ['Yumemiru Danshi wa Genjitsushugisha'], 517),
    new animeInfo("An Archdemon's Dilemma: How to Love Your Elf Bride", ['Maou no Ore ga Dorei Elf wo Yome ni Shitanda ga, Dou Medereba Ii?', 'How to Love Your Slave Elf Wife?'], 518),
    new animeInfo("GOOD NIGHT WORLD", ['GNW'], 519),
    new animeInfo("Ping Pong the Animation", ['PPTA'], 520),
    new animeInfo("Girls' Last Tour", ['GLT', 'Girls Last Tour', 'Shoujo Shuumatsu Ryokou'], 521),
    new animeInfo("Moriarty the Patriot", ['Yuukoku no Moriarty', 'MtP'], 522),
    new animeInfo("Hikaru no Go", ["Hikaru's Go", 'HnG'], 523),
    new animeInfo("Demon Lord, Retry!", ['Maou-sama, Retry!', 'Demon Lord Retry', 'Maou-sama Retry', 'MsR', 'DLR'], 524),
    new animeInfo("The Ping-Pong Club", ['Go! Ina Junior High Ping-Pong Club', 'Ike! Ina-chuu Takkyuubu', 'The Ping Pong Club', 'PPC'], 525),
    new animeInfo("More than a Married Couple, but Not Lovers.", ['More than a Couple, Less than Lovers.', 'Fuukoi', 'Fuufu Ijou, Koibito Miman'], 526),
    new animeInfo("Josee, the Tiger and the Fish", ['Josee to Tora to Sakana-tachi', 'JoseeTora'], 527),
    new animeInfo("Helck", [], 528),
    new animeInfo("Tenchi Muyo!", ['Tenchi Muyou', 'TM!'], 529),
    new animeInfo("Sakura Wars", ['Sakura Taisen'], 530),
    new animeInfo("Recovery of an MMO Junkie", ['Neto-juu no Susume', 'Netojuu no Susume', 'Recommendation of the Wonderful Virtual Life', 'Netoju'], 531),
    new animeInfo("Ergo Proxy", ['EP'], 532),
    new animeInfo("Ben-To", ['Bento', 'Ben-Tou'], 533),
    new animeInfo("Hatena☆Illusion", ['Hatena Illusion', 'HI'], 534),
    new animeInfo("Sentouin, Hakenshimasu!", ['Combatants Will Be Dispatched', 'SH!', 'Sentouin Hakenshimasu', 'CWBD'], 535),
    new animeInfo("Persona", ['Persona Series'], 536),
    new animeInfo("Urusei Yatsura", ['Those Obnoxious Aliens', 'Lum the Invader Girl', 'The Return of Lum', 'Lum', 'UY'], 537),
    new animeInfo("Saekano", ['Saekano: How to Raise a Boring Girlfriend', 'Saenai Heroine no Sodatekata'], 538),
    new animeInfo("Chrono Trigger", ["CT"], 539),
    new animeInfo("The Vexations of a Shut-In Vampire Princess", ['Hikikomari Kyuuketsuki no Monmon', "The Shut-in Vampire Princess' Worries", 'Hikikomari'], 540),
    new animeInfo("Mr. Villain's Day Off", ["Villain's Day Off", "Villains Day Off", "Villain-san's Day Off", 'Kyuujitsu no Warumono-san'], 541),
    new animeInfo("Handyman Saitou in Another World", ['Benriya Saitou-san, Isekai ni Iku'], 542),
    new animeInfo("Alya Sometimes Hides Her Feelings in Russian", ['Roshidere', 'Tokidoki Bosotto Roshia-go de Dereru Tonari no Alya-san', 'Tokidoki Bosotto Roshiago de Dereru Tonari no Alya-san', 'Alya, Who Sits Next to Me, Sometimes Whispers Sweet Nothings in Russian', 'The Neighboring Aarya-san who Sometimes Acts Affectionate and Murmuring in Russian'], 543),
    new animeInfo("Jellyfish Can't Swim in the Night", ['YoruKura', 'Yoru no Kurage wa Oyogenai'], 544),
    new animeInfo("The Great Cleric", ['Seija Musou: Salaryman, Isekai de Ikinokoru Tame ni Ayumu Michi', 'Seija Musou'], 545),
    new animeInfo("Saint Cecilia & Pastor Lawrence", ['The White Holy Woman and the Black Priest', 'White Saint and Black Pastor', 'Die Heilige Cecilia und Pastor Lawrence', 'Shiro Seijo to Kuro Bokushi', 'Saint Cecilia and Pastor Lawrence', 'Shiro Seijyo'], 546),
    new animeInfo("Rune Soldier", ['Magical Soldier Louie', 'Mahou Senshi Louie'], 547),
    new animeInfo("Nana", [], 548),
    new animeInfo("APPARE-RANMAN!", ['Appare Ranman!', 'Appare-Ranman!', 'AR!'], 549),
    new animeInfo("I'm Standing on a Million Lives", ['100-man no Inochi no Ue ni Ore wa Tatteiru', "I'm standing on 1,000,000 lives."], 550),
    new animeInfo("The Unwanted Undead Adventurer", ['Nozomanu Fushi no Boukensha', 'The Adventurer Who Received Undesired Immortality', 'The Unwanted Immortal Adventurer', 'TUUA'], 551),
    new animeInfo("Tales of Wedding Rings", ['Kekkon Yubiwa Monogatari', 'Wedding Ring Story'], 552),
    new animeInfo("The Wrong Way to Use Healing Magic", ['Chiyu Mahou no Machigatta Tsukaikata', 'ChiyuMahou'], 553),
    new animeInfo("The Foolish Angel Dances with the Devil", ['KanaTen', 'Oroka na Tenshi wa Akuma to Odoru', 'Stupid angel dances with the devil'], 554),
    new animeInfo("Ningen Fushin: Adventurers Who Don't Believe in Humanity Will Save the World", ['Apparently, Disillusioned Adventurers Will Save the World', 'Ningen Fushin no Boukensha-tachi ga Sekai wo Sukuu you desu', 'NFnB', "Ningen Fushin"], 555),
    new animeInfo("AHO-GIRL", ['Aho-Girl', 'Ahogaru: Clueless Girl', 'Dumb Girl'], 556),
    new animeInfo("Castle Town Dandelion", ['Joukamachi no Dandelion', 'JnD', 'Dande'], 557),
    new animeInfo("Sengoku Youko", [], 558),
    new animeInfo("Ninja Kamui", ['NK'], 559),
    new animeInfo("Wuthering Waves", ['WuWa', 'Ming Chao'], 560),
    new animeInfo("My Happy Marriage", ['The Shape of My Happiness', 'WataKon', 'Watashi no Shiawase na Katachi', 'Watashi no Shiawase na Kekkon'], 561),
    new animeInfo("The Girl Who Leapt Through Time", ['The Girl Who Cut Time', 'Toki wo Kakeru Shojo', 'Toki wo Kakeru Shoujo', 'TokiKake', 'TGWLTT'], 562),
    new animeInfo("Valvrave the Liberator", ['Kakumeiki Valvrave', 'VtL', 'KV'], 563),
    new animeInfo("Amagi Brilliant Park", ['Amaburi', 'ABP', 'AmaBri'], 564),
    new animeInfo("HEROMAN", ['Heroman'], 565),
    new animeInfo("Dan Da Dan", ["Dandadan", 'DDD'], 566),
    new animeInfo("Valkyria Chronicles", ['Senjou no Valkyria', 'VC'], 567),
    new animeInfo("Witch Hunter ROBIN", ['WHR'], 568),
    new animeInfo("SK8 the Infinity", ['SK Eight', 'SK∞'], 569),
    new animeInfo("Battle Through the Heavens", ['Dou Po Cang Qiong', 'Doupo Cangqiong', 'Fight Break Sphere', 'BTTH'], 570),
    new animeInfo("Snow White with the Red Hair", ['Akagami no Shirayuki-hime', 'Akagami no Shirayukihime', 'Bind Us', 'AnS'], 571),
    new animeInfo("Powerpuff Girls Z", ["And They're Off! Powerpuff Girls Z", 'Demashitaa! Powerpuff Girls Z', 'PPGZ'], 572),
    new animeInfo("Xie Wang Zhui Qi", ['King of Jin in Tang Dynasty', 'The Demonic King Who Chases His Wife'], 573),
    new animeInfo("Hokkaido Gals Are Super Adorable!", ['Dosakoi', 'Dosanko Gal wa Namara Menkoi', 'Dosanko Gyaru Is Mega Cute', 'Dosanko Gyaru wa Namaramenkoi', 'HGaSA', 'DGwN'], 574),
    new animeInfo("Metallic Rouge", [], 575),
    new animeInfo("Shin Chan", ['Crayon Shin-chan', 'Crayon Shinchan', 'Shinchan', 'Shin-chan'], 576),
    new animeInfo("The Helpful Fox Senko-san", ['Sewayaki Kitsune no Senko-san', 'Meddlesome Kitsune Senko-san', 'THFS', 'SKnS'], 577),
    new animeInfo("The Great Jahy Will Not Be Defeated!", ['Jahy-sama wa Kujikenai!', 'Niepokonana Jahy', "Jahy'sama won't be discouraged!", 'JwK'], 578),
    new animeInfo("Place to Place", ['Acchi Kocchi'], 579),
    new animeInfo("Gabriel DropOut", ['GabDro', 'GDO', 'GabDrop'], 580),
    new animeInfo("Idaten Jump", [], 581),
    new animeInfo("Ryuuou no Oshigoto!", ['RnO!', "The Ryuo's Work is Never Done!"], 582),
    new animeInfo("Bobobo-bo Bo-bobo", ['Boboboobo Boobobo', 'Boboboubo Boubobo', 'Bobobo'], 583),
    new animeInfo("Migi and Dali", ['Migi to Dali', 'Migi & Dali'], 584),
    new animeInfo("Kindergarten WARS", ['Kindergarten Wars', 'Youchien WARS'], 585),
    new animeInfo("Bokura wa Minna Kawai-sou", ['Bokura wa Minna Kawaisou', 'The Kawai Complex Guide to Manors and Hostel Behavior', 'BMK'], 586),
    new animeInfo("Psychic Squad", ['Absolutely Lovely Children', 'Unlimited Psychic Squad', 'ZKC', 'Zettai Karen Children', 'The Unlimited: Hyoubu Kyousuke'], 587),
    new animeInfo("CODE-E", [], 588),
    new animeInfo("The Book of Bantorra", ['Armed Librarians: The Book of Bantorra', 'Fighting Librarians', 'Tatakau Shisho', 'Tatakau Shisho to Koisuru Bakudan', 'Tatakau Shisho: The Book of Bantorra'], 589),
    new animeInfo("Fena: Pirate Princess", ['Kaizoku Oujo', 'FPP', 'Fena Pirate Princess'], 590),
    new animeInfo("R.O.D - READ OR DIE", ['R.O.D -READ OR DIE-', 'R.O.D -THE TV-', 'Read or Die', 'Read or Dream', 'R.O.D: Read or Dream', 'ROD'], 591),
    new animeInfo("Blood", ['BLOOD THE LAST VAMPIRE', 'BLOOD+', 'BLOOD-C', 'Blood Plus', 'Blood: The Last Vampire'], 592),
    new animeInfo("Sabikui Bisco", ['Bisco Si Pemakan Karat', 'Rust-Eater Bisco'], 593),
    new animeInfo("Gun x Sword", ['Gun vs Sword', 'Gun x Sword-san', 'GxS', 'Gun and Sword', 'Gun times Sword'], 594),
    new animeInfo("I Was Reincarnated as the 7th Prince So I Can Take My Time Perfecting My Magical Ability", ['Dainanaoji', 'Tensei Shitara Dai Nana Ouji Dattanode', 'Tensei Shitara Dai Nana Ouji Dattanode, Kimamani Majutsu wo Kiwamemasu', 'I Was Reincarnated As the 7th Prince so I Will Perfect My Magic As I Please', 'TenOuji'], 595),
    new animeInfo("Outlaw Star", ['Future Hero Next Generation Outlaw Star', 'Seihou Bukyou Outlaw Star', 'Starward Warrior Knight Outlaw Star'], 596),
    new animeInfo("Arpeggio of Blue Steel", ['Aoki Hagane no Arpeggio', 'Aoki Hagane no Arpeggio: Ars Nova - Cadenza', 'Aoki Hagane no Arpeggio: Ars Nova - DC', 'Arpeggio of Blue Steel - Cadenza', 'Arpeggio of Blue Steel - DC', 'AoBS'], 597),
    new animeInfo("Koto oto Tomare", ["Stop This Sound"], 598),
    new animeInfo("Beast Tamer", ['Yuusha Party wo Tsuihou Sareta Beast Tamer, Saikyoushu no Nekomimi Shoujo to Deau', 'Beast Tamer and the Cat Girl'], 599),
    new animeInfo("Cardcaptor Sakura", ["Kadokyaputa Sakura"], 600),
    new animeInfo("I am getting married to a girl I hate in my class", ["Kurakon", "Class no Daikirai na Joshi to Kekkon suru Koto ni Natta.", " I Got Married to the Girl I Hate Most in Class"], 601),
    new animeInfo("Sengoku BASARA", ['SB1', 'Devil Kings'], 602),
    new animeInfo("Dies irae", ['Day of Wrath', 'Di'], 603),
    new animeInfo("EDENS ZERO", ['EZ', "Eden's Zero", 'EDENSZERO'], 604),
    new animeInfo("Re:Monster", ['Re:Monster Shisatsu Kara Hajimaru Kaibutsu Tensei-ki', 'R:M', 'Stabbed to Death', 'Reincarnated: Monster'], 605),
    new animeInfo("Tears to Tiara", [], 606),
    new animeInfo("Katsute Mahou Shoujo to Aku wa Tekitai shiteita", ["The Magical Girl and the Evil Lieutenant Used to Be Archenemies", "Katsute Mahou Shoujo to Aku wa Tekitai Shite Ita.", "The Former Magical Girl & Evil Enemy", "The Magical Girl and Evil Officer", "MahoAku"], 607),
    new animeInfo("Medaka Kuroiwa Is Impervious to My Charms", ["Kuroiwa Medaka ni Watashi no Kawaii ga Tsuujinai", "Medakawa", "My Charms Are Wasted On Kuroiwa Medaka"], 608),
    new animeInfo("Legend of the Northern Blade", ["Bukgeom Jeongi", "The Legend of the Northern Blade", "Legend of the Northen Blade"], 609),

];



// Check if duplicate names
{
    // let names = characters.map((e) => e.name).sort();
    let names = anime.reduce<string[]>((acc, ani) => [...acc, ani.name, ...ani.alias], []).sort();
    let len = names.length - 1, res = "";
    while (len--) if (names[len - 1] === names[len]) res += names[len--] + "\n";
    if (res) throw new Error("WARNING! Duplicate names in anime: " + res);
}

// Check gender, rarity and ID
anime.forEach((e, i) => {
    if (e.id !== i) throw new Error("WARNING! Wrong ID in anime " + e.id + " in: " + e.name);
});
